name: vaultify
description: A cool flutter app by uncool corpses
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  flex_seed_scheme: ^1.4.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  go_router: ^11.1.4
  google_fonts: ^6.1.0
  heroicons: ^0.9.0
  hydrated_bloc: ^9.1.2
  intl: ^0.18.0
  path_provider: ^2.1.1

dev_dependencies:
  bloc_test: ^9.1.4
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.5
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
  - assets/
  - assets/images/
  - assets/fonts/   

flutter_assets:
  assets_path: assets/
  output_path: lib/src/generated/
  filename: assets.dart


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21 